version: 3

tasks:
  deploy:localhost:
    desc: Deploy Metallb loadbalancer service manager
    summary: >
      Provision MetalLB with an address pool allocated to the internet routable IP address
    vars:
      IP_ADDRESS:
        sh: ip route get '1.1.1.1' | grep -oP 'src \K[^ ]+'
    cmds:
      - cmd: helm repo add metallb https://metallb.github.io/metallb
      - cmd: helm repo update
      - cmd: |
          helm upgrade --install metallb \
          --namespace metallb-system --create-namespace \
          --wait \
          metallb/metallb
      - cmd: |
          cat <<EOF | kubectl apply -f -
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{.IP_ADDRESS}}/32
          EOF
